version: '3.8'

services:
  # Frontend Service
  frontend:
    image: harri665/mern-frontend:latest
    container_name: cu3d-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:3001}
    depends_on:
      - backend
    networks:
      - cu3d-network
    restart: unless-stopped

  # Backend Service
  backend:
    image: harri665/mern-backend:latest
    container_name: cu3d-backend
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-root}:${MONGO_PASSWORD:-example}@mongo:27017/${MONGO_DATABASE:-mst}?authSource=admin
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - DISCORD_TOKEN=${DISCORD_TOKEN:-disabled}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID:-1215926213839945778}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID:-509513851994374149}
    depends_on:
      - mongo
    networks:
      - cu3d-network
    restart: unless-stopped
    # Simplified health check
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/localhost/3001' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Service
  mongo:
    image: mongo:${MONGO_VERSION:-4.4}
    container_name: cu3d-mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-example}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-mst}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cu3d-network
    restart: unless-stopped
    # Simplified MongoDB health check
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  cu3d-network:
    driver: bridge
    name: cu3d-network
