version: '3.8'

services:
  backend:
    image: harri665/mern-backend
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/mst?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - app-network
    command: sh -c "sleep 10 && npm start" # Delay to ensure MongoDB is ready

  frontend:
    image: harri665/mern-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
