version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mern_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build: ./
    container_name: mern_server
    restart: always
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/mydatabase?authSource=admin
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: mern_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo_data:
