name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Modify the proxy in ./client/package.json
    - name: Update proxy in package.json
      run: |
        sed -i 's|"proxy": "http://localhost:3001"|"proxy": "http://backend:3001"|' ./client/package.json

    # Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # Build and push backend Docker image
    - name: Build and push backend Docker image
      run: |
        docker build -t harri665/mern-backend .
        docker push harri665/mern-backend

    # Build and push frontend Docker image
    - name: Build and push frontend Docker image
      run: |
        docker build -t harri665/mern-frontend ./client
        docker push harri665/mern-frontend
