name: Replace Proxy in Package.json

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace proxy in package.json
        run: |
          sed -i 's|"proxy": "http://localhost:3001"|"proxy": "http://backend:3001"|' ./client/package.json

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./client/package.json
          git commit -m "Update proxy in package.json to backend:3001"
          git push
